export interface User {
  id: string;
  firebase_uid: string;
  username: string;
  email: string;
  display_name: string;
  bio?: string;
  profile_picture_url?: string;
  banner_url?: string;
  is_verified: boolean;
  account_status?: "active" | "suspended" | "banned" | "pending_review" | "deleted";
  suspension_reason?: string | null;
  suspended_until?: string | null;
  community_strike_count?: number;
  copyright_strike_count?: number;
  last_strike_at?: string | null;
  two_factor_enabled?: boolean;
  last_password_change_at?: string | null;
  last_activity_at?: string | null;
  signup_ip?: string | null;
  last_login_ip?: string | null;
  last_login_user_agent?: string | null;
  date_of_birth?: string | null;
  country_code?: string;
  region?: string | null;
  is_premium: boolean;
  premium_status?: "none" | "trial" | "active" | "past_due" | "canceled";
  premium_plan?: string | null;
  premium_started_at?: string | null;
  premium_expires_at?: string | null;
  channel_created_at?: string;
  primary_channel_id?: number | null;
  subscriber_count?: number;
  total_views?: number;
  video_count?: number;
  is_private: boolean;
  allow_comments: boolean;
  marketing_emails_opt_in?: boolean;
  data_processing_consent?: boolean;
  accepted_terms_version?: string;
  accepted_terms_at?: string | null;
  accepted_privacy_version?: string;
  accepted_privacy_at?: string | null;
  created_at: string;
  updated_at: string;
  last_login_at?: string | null;
  deleted_at?: string | null;
  token?: string | null;
}

